#!/bin/sh

# :::::::.   .::::::.::::::::::. .::    .   .:::.        :   
#  ;;;'';;' ;;;`    ` `;;;```.;;;';;,  ;;  ;;;' ;;,.    ;;;  
#  [[[__[[\.'[==/[[[[, `]]nnn]]'  '[[, [[, [['  [[[[, ,[[[[, 
#  $$""""Y$$  '''    $  $$$""       Y$c$$$c$P   $$$$$$$$"$$$ 
# _88o,,od8P 88b    dP  888o         "88"888    888 Y88" 888o
# ""YUMMMP"   "YMmMY"   YMMMb         "M "M"    MMM  M'  "MMM

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
~/.fehbg &
dunst_update &
picom -bCG &
xautolock -time 3 -locker slock &
pgrep -x mpd > /dev/null || mpd ~/.config/mpd/mpd.conf &
pidof -s kitty > /dev/null || kitty --name=scratch --title=scratch --class=scratch &


bspc monitor -d 1 2 3 4 5 6 7  

 # BSPWM config 
 bspc config border_width                  2
 bspc config window_gap                    8
 bspc config top_padding                   0
 bspc config bottom_padding                0
 bspc config left_padding                  0
 bspc config right_padding                 0
 bspc config single_monocle                false
 bspc config click_to_focus                true
 bspc config split_ratio                   0.52
 bspc config borderless_monocle            true
 bspc config gapless_monocle               true
 bspc config focus_by_distance             true
 bspc config focus_follows_pointer         true
 bspc config history_aware_focus           true
 bspc config remove_disabled_monitors      true
 bspc config merge_overlapping_monitors    true
 bspc config automatic_scheme              alternate 
 bspc config gapless_monocle               false
 bspc config pointer_modifier mod4
 bspc config pointer_action1 move
 bspc config pointer_action2 resize_side
 bspc config pointer_action3 resize_corner

 bspc config normal_border_color         #131213
 bspc config active_border_color         #8ca68c
 bspc config focused_border_color        #8ca68c
 bspc config presel_feedback_color       #8ca68c


# Rules

bspc rule -a audio sticky=on state=floating
bspc rule -a *:audio sticky=on state=floating 
bspc rule -a scratch sticky=on state=floating hidden=on
bspc rule -a *:scratch sticky=on state=floating hidden=on
bspc rule -a ranger sticky=on state=floating 
bspc rule -a mpv =on sticky=on state=floating
bspc rule -a feh:* state=floating
